docker-taurus-latest:
  # Official docker image.
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASS} 
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" -t symbiote/docker-jmeter-ui:latest .
    - docker push "$CI_REGISTRY_IMAGE"
    - docker push symbiote/docker-jmeter-ui:latest
  only:
    - master

